version: '3.9'
services:
  trex-budget-bot:
    build: .
    container_name: trex-budget-bot
    ports:
      - "8080:8080"
    env_file: ".env"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USER: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      LOKI: http://loki:3100  # Это для logback.xml
    depends_on:
      - database
    volumes:
      - app-data:/app/logs
    networks:
      - monitoring

  database:
    image: postgres:latest
    container_name: database
    env_file: ".env"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tgbotdata"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  app-data:
  postgres-data:

networks:
  monitoring:
    external: true
#Создание сети
#  docker network create monitoring
