spring:
  application:
    name: trex-budget-bot
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  config:
#    activate:
#      on-profile: local
#    import: optional:secret.properties[.properties]
bot:
  botUsername: ${BOT_NAME}
  botToken: ${BOT_TOKEN}